### ISSUE TITLE
Provide requirements

### ISSUE THREAD

**Issue by detkov** [csxmli2016/DFDNet#1]
Hi! Thanks for open-sourcing such a perspective work!

I'm trying to test it in Colab and having some issues with CUDA on the last step (`test_FaceDict.py`).
Can you please provide us with some environment and requirements that can be used to reevaluate results?

Error:
```
----------------- Options ---------------
<Some options>
----------------- End -------------------
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "test_FaceDict.py", line 88, in <module>
    opt = TestOptions().parse()
  File "/content/DFDNet/options/base_options.py", line 114, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:59
```

**Comment by csxmli2016** [comment]
> Hi! Thanks for open-sourcing such a perspective work!
> 
> I'm trying to test it in Colab and having some issues with CUDA on the last step (`test_FaceDict.py`).
> Can you please provide us with some environment and requirements that can be used to reevaluate results?
> 
> Error:
> 
> ```
> ----------------- Options ---------------
> <Some options>
> ----------------- End -------------------
> THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
> Traceback (most recent call last):
>   File "test_FaceDict.py", line 88, in <module>
>     opt = TestOptions().parse()
>   File "/content/DFDNet/options/base_options.py", line 114, in parse
>     torch.cuda.set_device(opt.gpu_ids[0])
>   File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 281, in set_device
>     torch._C._cuda_setDevice(device)
> RuntimeError: cuda runtime error (101) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:59
> ```

Hi, thanks for your suggestions. I found the problem is common in different environments. You can refer to [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/360).

I use pytorch1.3 in this work and it runs successfully.

**Comment by detkov** [comment]
Thanks, but what CUDA, cuDNN, torchvision and numpy versions do you use?

**Comment by csxmli2016** [comment]
> Thanks, but what CUDA, cuDNN, torchvision and numpy versions do you use?

Hi, I have updated the pytorch version to 1.5. The new environment is shown below.
- CUDA is 10.2. 
- cuDNN version can be referred to [version](https://developer.nvidia.com/rdp/cudnn-archive). I use v7.6.5.
- torchvision is 0.6.
All these are installed by the official instruction. I think you can install pytorch (≥1.1) with [the official  instruction](https://pytorch.org/get-started/previous-versions/).
As for numpy, I use v1.18.
