### ISSUE TITLE
Error in enhancing this image

### ISSUE THREAD

**Issue by LingMoe404** [csxmli2016/DFDNet#14]
Im using nvdia 2070 and amd 2700, and i got this error report😭How to solve it.
我现在是N卡2070和AU2700，第三步就报错显存不够，CPU模式用不了，请问要怎么解决啊😭泪，拉了出来。

Error in enhancing this image: CUDA out of memory. Tried to allocate 758.00 MiB (GPU 0; 8.00 GiB total capacity; 3.78 GiB already allocated; 674.04 MiB free; 4.99 GiB reserved in total by PyTorch)

![image](https://user-images.githubusercontent.com/54352563/90390441-ea25ad80-e0bd-11ea-963f-491b8b28a548.png)
![image](https://user-images.githubusercontent.com/54352563/90390479-f7429c80-e0bd-11ea-8f70-555ac1dc107b.png)

**Comment by csxmli2016** [comment]
> Im using nvdia 2070 and amd 2700, and i got this error report😭How to solve it.
> 我现在是N卡2070和AU2700，第三步就报错显存不够，CPU模式用不了，请问要怎么解决啊😭泪，拉了出来。
> 
> Error in enhancing this image: CUDA out of memory. Tried to allocate 758.00 MiB (GPU 0; 8.00 GiB total capacity; 3.78 GiB already allocated; 674.04 MiB free; 4.99 GiB reserved in total by PyTorch)
> 
> ![image](https://user-images.githubusercontent.com/54352563/90390441-ea25ad80-e0bd-11ea-963f-491b8b28a548.png)
> ![image](https://user-images.githubusercontent.com/54352563/90390479-f7429c80-e0bd-11ea-8f70-555ac1dc107b.png)

cpu模式为啥用不了啊。。。显存不够。。应该没法解决吧。。可能需要个显存再大一些的卡

**Comment by abarkanium** [comment]
thanks for this excellent repo , now it works with GPU , But only in step 2 - 3 , the first step is still slow :(

**Comment by csxmli2016** [comment]
> thanks for this excellent repo , now it works with GPU , But only in step 2 - 3 , the first step is still slow :(

The first step can only run on cpu mode and it takes some time to detect five landmarks, compute the affine parameters and crop face, etc. I will pay attention to these related methods and try to accelerate the running speed in the future. But I am not sure whether I have time these days.

**Comment by LingMoe404** [comment]
> > Im using nvdia 2070 and amd 2700, and i got this error report😭How to solve it.
> > 我现在是N卡2070和AU2700，第三步就报错显存不够，CPU模式用不了，请问要怎么解决啊😭泪，拉了出来。
> > Error in enhancing this image: CUDA out of memory. Tried to allocate 758.00 MiB (GPU 0; 8.00 GiB total capacity; 3.78 GiB already allocated; 674.04 MiB free; 4.99 GiB reserved in total by PyTorch)
> > ![image](https://user-images.githubusercontent.com/54352563/90390441-ea25ad80-e0bd-11ea-963f-491b8b28a548.png)
> > ![image](https://user-images.githubusercontent.com/54352563/90390479-f7429c80-e0bd-11ea-8f70-555ac1dc107b.png)
> 
> cpu模式为啥用不了啊。。。显存不够。。应该没法解决吧。。可能需要个显存再大一些的卡

CPU模式也报cuda显存不够，不知道为什么……可能是因为我是AMD的cpu没核显吗？

**Comment by csxmli2016** [comment]
> > > Im using nvdia 2070 and amd 2700, and i got this error report😭How to solve it.
> > > 我现在是N卡2070和AU2700，第三步就报错显存不够，CPU模式用不了，请问要怎么解决啊😭泪，拉了出来。
> > > Error in enhancing this image: CUDA out of memory. Tried to allocate 758.00 MiB (GPU 0; 8.00 GiB total capacity; 3.78 GiB already allocated; 674.04 MiB free; 4.99 GiB reserved in total by PyTorch)
> > > ![image](https://user-images.githubusercontent.com/54352563/90390441-ea25ad80-e0bd-11ea-963f-491b8b28a548.png)
> > > ![image](https://user-images.githubusercontent.com/54352563/90390479-f7429c80-e0bd-11ea-8f70-555ac1dc107b.png)
> > 
> > 
> > cpu模式为啥用不了啊。。。显存不够。。应该没法解决吧。。可能需要个显存再大一些的卡
> 
> CPU模式也报cuda显存不够，不知道为什么……可能是因为我是AMD的cpu没核显吗？

哎，我也不知道咋回事了，我找了几台电脑用cpu测试了下也能正常运行，不过有人用[google colab](https://github.com/csxmli2016/DFDNet/issues/17#issue-680671802)实现了一下，你可以试试。

**Comment by LingMoe404** [comment]
> > > > Im using nvdia 2070 and amd 2700, and i got this error report😭How to solve it.
> > > > 我现在是N卡2070和AU2700，第三步就报错显存不够，CPU模式用不了，请问要怎么解决啊😭泪，拉了出来。
> > > > Error in enhancing this image: CUDA out of memory. Tried to allocate 758.00 MiB (GPU 0; 8.00 GiB total capacity; 3.78 GiB already allocated; 674.04 MiB free; 4.99 GiB reserved in total by PyTorch)
> > > > ![image](https://user-images.githubusercontent.com/54352563/90390441-ea25ad80-e0bd-11ea-963f-491b8b28a548.png)
> > > > ![image](https://user-images.githubusercontent.com/54352563/90390479-f7429c80-e0bd-11ea-8f70-555ac1dc107b.png)
> > > 
> > > 
> > > cpu模式为啥用不了啊。。。显存不够。。应该没法解决吧。。可能需要个显存再大一些的卡
> > 
> > 
> > CPU模式也报cuda显存不够，不知道为什么……可能是因为我是AMD的cpu没核显吗？
> 
> 哎，我也不知道咋回事了，我找了几台电脑用cpu测试了下也能正常运行，不过有人用[google colab](https://github.com/csxmli2016/DFDNet/issues/17#issue-680671802)实现了一下，你可以试试。

好的呢 谢谢你
