### ISSUE TITLE
RuntimeError: invalid device ordinal

### ISSUE THREAD

**Issue by GuusDeKroon** [csxmli2016/DFDNet#7]
After running "python test_FaceDict.py", I get this message, but I can't seem to fix it. My GPU(0) is a 2080ti

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1595629427286/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "test_FaceDict.py", line 88, in <module>
    opt = TestOptions().parse()
  File "/home/nextface/DFDNet/options/base_options.py", line 114, in parse
    torch.cuda.set_device(opt.gpu_ids[0])
  File "/home/nextface/miniconda3/envs/DFD/lib/python3.6/site-packages/torch/cuda/__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1595629427286/work/torch/csrc/cuda/Module.cpp:59

**Comment by csxmli2016** [comment]
> invalid device ordinal at /opt/conda/conda-bld/pytorch_1595629427286/work/torch/csrc/cuda/Module.cpp:59

Hi, I am not sure about this error. Maybe this is caused by the inconsistent package version. But you can run it in cpu by setting ```opt.gpu_ids = []```  [in line 100.](https://github.com/csxmli2016/DFDNet/blob/94d55951961bbdc7cb72d460ab9bda545cb72029/test_FaceDict.py#L100)

**Comment by Lubsey1** [comment]
I had this issue, fixed it by switching default gpu on line 22 of base_options.py to (0) rather than (1,3)

**Comment by csxmli2016** [comment]
> I had this issue, fixed it by switching default gpu on line 22 of base_options.py to (0) rather than (1,3)
> `parser.add_argument('--gpu_ids', type=str, default='0', help='gpu ids: e.g. 0 0,1,2, 0,2. use -1 for CPU')`

Thanks very much. I have updated the bas_options.py file.
